version: 2
services:
  redis:
    image: redis
    networks:
      - backend

  db:
    image: postgres
    networks:
      - backend

  vote_app:
    build: ./vote 
    ports:
      - "6000:80"
    depend_on:
      - redis
    networks:
      - backend
      - frontend

  result:
    build: ./result
    ports:
      - "6001:80"
    depend_on:
      - db
    networks:
      - backend
      - frontend

  worker:
    build: ./worker
    depend_on:
      - redis
      - db
    networks:
      - backend

networks:
  frontend
  backend
