
redis:
  image:redis

db:
  image:postgres

vote_app:
  image:"voting_app"
  ports:
    - "6000:80"
  links:
    - redis

result:
  image:"result_app"
  ports:
    - "6001:80"
  links:
    - db

worker:
  image:"worker_app"
  links:
    - redis
    - db
